import type { Metadata } from "next";
import { Geist_Mono, Climate_Crisis, Murecho } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const murecho = Murecho({
  variable: "--font-murecho",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const climateCrisis = Climate_Crisis({
  variable: "--font-climate",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${murecho.variable} ${geistMono.variable} ${climateCrisis.variable} font-[family-name:var(--font-murecho)] antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
